apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-data-pvc # A descriptive name for your PVC
  namespace: sonarqube    # The same namespace as your SonarQube deployment
spec:
  accessModes:
    - ReadWriteOnce # Or ReadWriteMany depending on your needs and storage class
  storageClassName: default # Or your preferred StorageClass
  resources:
    requests:
      storage: 10Gi # Adjust the size based on your needs