apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: sonarqube
  labels:
    app: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: sonarqube
          image: sonarqube:community
          ports:
            - containerPort: 9000
          env:
            - name: SONAR_ES_BOOTSTRAP_CHECKS_DISABLE
              value: "true"
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "500m"
          volumeMounts:
            - name: sonarqube-persistent-storage # Name matching the volume
              mountPath: /opt/sonarqube/data # The path inside the SonarQube container where data is stored
      volumes:
        - name: sonarqube-persistent-storage # Name referenced in volumeMounts
          persistentVolumeClaim:
            claimName: sonarqube-data-pvc # The name of the PVC you created
